# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import p2p_pb2 as p2p__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in p2p_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class P2PStub(object):
    """comunication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Comunicate = channel.unary_unary(
                '/p2p.P2P/Comunicate',
                request_serializer=p2p__pb2.Request.SerializeToString,
                response_deserializer=p2p__pb2.Respond.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/p2p.P2P/Connect',
                request_serializer=p2p__pb2.Request.SerializeToString,
                response_deserializer=p2p__pb2.Respond.FromString,
                _registered_method=True)
        self.SearchID = channel.unary_unary(
                '/p2p.P2P/SearchID',
                request_serializer=p2p__pb2.Request.SerializeToString,
                response_deserializer=p2p__pb2.Respond.FromString,
                _registered_method=True)


class P2PServicer(object):
    """comunication
    """

    def Comunicate(self, request, context):
        """functions to send info and respond
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """connect to the ring
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchID(self, request, context):
        """searchID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_P2PServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Comunicate': grpc.unary_unary_rpc_method_handler(
                    servicer.Comunicate,
                    request_deserializer=p2p__pb2.Request.FromString,
                    response_serializer=p2p__pb2.Respond.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=p2p__pb2.Request.FromString,
                    response_serializer=p2p__pb2.Respond.SerializeToString,
            ),
            'SearchID': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchID,
                    request_deserializer=p2p__pb2.Request.FromString,
                    response_serializer=p2p__pb2.Respond.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'p2p.P2P', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('p2p.P2P', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class P2P(object):
    """comunication
    """

    @staticmethod
    def Comunicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.P2P/Comunicate',
            p2p__pb2.Request.SerializeToString,
            p2p__pb2.Respond.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.P2P/Connect',
            p2p__pb2.Request.SerializeToString,
            p2p__pb2.Respond.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.P2P/SearchID',
            p2p__pb2.Request.SerializeToString,
            p2p__pb2.Respond.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
