# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2p.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'p2p.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tp2p.proto\x12\x03p2p\"Y\n\x07Request\x12\x0f\n\x07self_id\x18\x01 \x01(\x05\x12\x13\n\x0bself_socket\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0e\n\x06socket\x18\x04 \x01(\t\x12\x0c\n\x04info\x18\x05 \x01(\t\"Y\n\x07Respond\x12\x0f\n\x07self_id\x18\x01 \x01(\x05\x12\x13\n\x0bself_socket\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0e\n\x06socket\x18\x04 \x01(\t\x12\x0c\n\x04info\x18\x05 \x01(\t2~\n\x03P2P\x12(\n\nComunicate\x12\x0c.p2p.Request\x1a\x0c.p2p.Respond\x12%\n\x07\x43onnect\x12\x0c.p2p.Request\x1a\x0c.p2p.Respond\x12&\n\x08SearchID\x12\x0c.p2p.Request\x1a\x0c.p2p.Respondb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=18
  _globals['_REQUEST']._serialized_end=107
  _globals['_RESPOND']._serialized_start=109
  _globals['_RESPOND']._serialized_end=198
  _globals['_P2P']._serialized_start=200
  _globals['_P2P']._serialized_end=326
# @@protoc_insertion_point(module_scope)
